### PR TITLE
nmaahcmm-v0.0.6

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by BleakleyMcD** [comment]
@dericed ok this worked. Thanks! Why did we need to make a new release?

**Comment by dericed** [comment]
cuz these commits happened since the last release. https://github.com/NMAAHC/nmaahcmm/compare/nmaahcmm-v0.0.5...nmaahcmm-v0.0.6

**Comment by BleakleyMcD** [comment]
Ya, but I thought there was something like `brew install --HEAD` that let you access the latest commits without having to make a new release... otherwise you have to make new releases all the time. Does --HEAD or whatever it was no longer exist? @dericed

**Comment by dericed** [comment]
Making releases all the time ain't too bad. Incremental numbers are still pretty easy to get, or if you run low, there's a [spot](https://brooklynintegers.com/) in Brooklyn that hand crafts them.

**Comment by BleakleyMcD** [comment]
haha. Last time I checked mayonnaise wasn't a number.

**Pull request merged**
